### ISSUE TITLE
Fix alignment

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparkdefi-frontend#20]
![image](https://user-images.githubusercontent.com/61826995/132650450-f246896e-d0bd-4861-a10a-a97161ba4762.png)

**Comment by medardm** [comment]
![Screen Shot 2021-09-10 at 4 39 08 PM](https://user-images.githubusercontent.com/20562573/132829647-c70a32c5-c536-4d0a-984a-8a4687253522.png)
![Screen Shot 2021-09-10 at 4 39 23 PM](https://user-images.githubusercontent.com/20562573/132829657-f484d471-43d2-43e4-a79e-c22679ccdedb.png)
