### ISSUE TITLE
Fetch user balance

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparkdefi-frontend#25]
![image](https://user-images.githubusercontent.com/61826995/132664559-0188ce89-0c4b-4900-8d31-a4eff4b95f7b.png)

**Comment by mativanarquero** [comment]
Ang dinisplay ko dito sir @swengr-janan is yung yung actual fullbalance value na. Di po nagrereflect actual balance mo?

**Comment by swengr-janan** [comment]
Yung lahat ng LP token balance nya Mat

**Comment by swengr-janan** [comment]
Ah, wala kasi akong LP tokens kaya palagi yun 0

**Comment by mativanarquero** [comment]
Ang hindi nalang po sir @swengr-janan dynamic sa staking modal sa farms is yung approved tokens

**Comment by swengr-janan** [comment]
Nice nice. Sige Mat, confirm ko nalang tong issue kapag naka add na ako LP Staking. Work out mo na din yung ibang naka static pa
